function PlotDisplacements(t, Rcggs)
    n = numel(t);
    % [] Number of elements in the time vector.

    %— pre‐allocate the four traces:
    dE = zeros(1,n);    % East
    dN = zeros(1,n);    % North
    dZ = zeros(1,n);    % Zenith
    R  = zeros(1,n);    % Linear range

    for k = 1:n
        dE(k) = Rcggs(1,k);
        dN(k) = Rcggs(2,k);
        dZ(k) = Rcggs(3,k);
        R(k)  = sqrt(dE(k)^2 + dN(k)^2);
    end
    % [] Extracts ENZ displacements and computes range.

    Window = figure( ...
        'Color','w', ...
        'Name','Displacements (E/N/Z/Linear)', ...
        'NumberTitle','Off');
    % [] New figure window.

    % common x settings
    xlim_   = [0,70];
    xtick_  = 0:7:70;

    %% 1) East subplot
    ax1 = subplot(2,2,1,'Parent',Window);
    set(ax1, ...
        'FontName','Arial','FontSize',8,'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'XGrid','On','YGrid','On', ...
        'XLim',xlim_, 'XTick',xtick_, ...
        'YLim',[0,7000], 'YTick',0:700:7000);
    % [] Axes properties for “East”

    plot(t, dE, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',ax1);
    % [] Plot East vs. Time

    title(ax1, 'East', ...
        'FontName','Arial','FontSize',16,'FontWeight','Bold');
    xlabel(ax1, 'Time (s)', ...
        'FontName','Arial','FontSize',12,'FontWeight','Bold');
    ylabel(ax1, 'Displacement (m)', ...
        'FontName','Arial','FontSize',12,'FontWeight','Bold');


    %% 2) North subplot
    ax2 = subplot(2,2,2,'Parent',Window);
    set(ax2, ...
        'FontName','Arial','FontSize',8,'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'XGrid','On','YGrid','On', ...
        'XLim',xlim_, 'XTick',xtick_, ...
        'YLim',[-2500,0], 'YTick',-2500:250:0);
    % [] Axes properties for “North”

    plot(t, dN, ...
        'Color','k','LineStyle','None','Marker','.', ...
        'Parent',ax2);
    title(ax2, 'North', ...
        'FontName','Arial','FontSize',16,'FontWeight','Bold');
    xlabel(ax2, 'Time (s)', ...
        'FontName','Arial','FontSize',12,'FontWeight','Bold');
    ylabel(ax2, 'Displacement (m)', ...
        'FontName','Arial','FontSize',12,'FontWeight','Bold');


    %% 3) Zenith subplot
    ax3 = subplot(2,2,3,'Parent',Window);
    set(ax3, ...
        'FontName','Arial','FontSize',8,'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'XGrid','On','YGrid','On', ...
        'XLim',xlim_, 'XTick',xtick_, ...
        'YLim',[0,6000], 'YTick',0:600:6000);
    % [] Axes properties for “Zenith”

    plot(t, dZ, ...
        'Color','k','LineStyle','None','Marker','.', ...
        'Parent',ax3);
    title(ax3, 'Zenith', ...
        'FontName','Arial','FontSize',16,'FontWeight','Bold');
    xlabel(ax3, 'Time (s)', ...
        'FontName','Arial','FontSize',12,'FontWeight','Bold');
    ylabel(ax3, 'Displacement (m)', ...
        'FontName','Arial','FontSize',12,'FontWeight','Bold');


    %% 4) Linear Range subplot
    ax4 = subplot(2,2,4,'Parent',Window);
    set(ax4, ...
        'FontName','Arial','FontSize',8,'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'XGrid','On','YGrid','On', ...
        'XLim',xlim_, 'XTick',xtick_, ...
        'YLim',[0,8000], 'YTick',0:800:8000);
    % [] Axes properties for “Linear”

    plot(t, R, ...
        'Color','k','LineStyle','None','Marker','.', ...
        'Parent',ax4);
    title(ax4, 'Linear', ...
        'FontName','Arial','FontSize',16,'FontWeight','Bold');
    xlabel(ax4, 'Time (s)', ...
        'FontName','Arial','FontSize',12,'FontWeight','Bold');
    ylabel(ax4, 'Range (m)', ...
        'FontName','Arial','FontSize',12,'FontWeight','Bold');

end
