function PlotAzEl(t, Rcggs)
% Plots Azimuth & Elevation vs. Time in a 2×1 subplot
%
% Inputs:
%   t      – [1×n] time vector (s)
%   Rcggs  – [3×n] ENZ position (m) w.r.t. GS

    n = numel(t);
    % [] Number of elements in the time vector.

    %— compute az/el in degrees
    az  = zeros(1,n);
    el  = zeros(1,n);
    for k = 1:n
        E = Rcggs(1,k);
        N = Rcggs(2,k);
        Z = Rcggs(3,k);
        az(k) = atan2(E, N);                   % rad east of north
        el(k) = asin( Z / norm([E;N;Z]) );     % rad above horizon
    end
    az = rad2deg(az);
    el = rad2deg(el);
    % [] Convert radians → degrees

    Window = figure( ...
        'Color','w', ...
        'Name','Azimuth & Elevation', ...
        'NumberTitle','Off');
    % [] New white figure window.

    % common x‐axis settings
    xlim_  = [0,70];
    xtick_ = 0:7:70;

    %% Azimuth subplot
    ax1 = subplot(2,1,1,'Parent',Window);
    set(ax1, ...
        'FontName','Arial',    ...
        'FontSize',8,          ...
        'FontWeight','Bold',   ...
        'NextPlot','Add',      ...
        'XGrid','On',          ...
        'YGrid','On',          ...
        'XLim', xlim_,         ...
        'XTick', xtick_,       ...
        'YLim', [-180,180],    ...
        'YTick', -180:36:180);
    % [] Axes props for “Azimuth”

    plot(t, az, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',ax1);
    % [] Plot Azimuth vs. time

    title(ax1, 'Azimuth', ...
        'FontName','Arial', ...
        'FontSize',16, ...
        'FontWeight','Bold');
    xlabel(ax1, 'Time (s)', ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold');
    ylabel(ax1, 'Azimuth (°)', ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold');


    %% Elevation subplot
    ax2 = subplot(2,1,2,'Parent',Window);
    set(ax2, ...
        'FontName','Arial',    ...
        'FontSize',8,          ...
        'FontWeight','Bold',   ...
        'NextPlot','Add',      ...
        'XGrid','On',          ...
        'YGrid','On',          ...
        'XLim', xlim_,         ...
        'XTick', xtick_,       ...
        'YLim', [-90,90],      ...
        'YTick', -90:18:90);
    % [] Axes props for “Elevation”

    plot(t, el, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',ax2);
    % [] Plot Elevation vs. time

    title(ax2, 'Elevation', ...
        'FontName','Arial', ...
        'FontSize',16, ...
        'FontWeight','Bold');
    xlabel(ax2, 'Time (s)', ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold');
    ylabel(ax2, 'Elevation (°)', ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold');

end
