function PlotInertialAcceleration(t, Rcggs, Vcggs, C)
% Plots the true inertial acceleration (Earth frame) vs. time in g's
%
% Inputs:
%   t      – [1×n] time vector (s)
%   Rcggs  – [3×n] ENZ position w.r.t. GS (m)
%   Vcggs  – [3×n] ENZ velocity w.r.t. GS (m/s)
%   C      – constants struct

    n = numel(t);
    % [] Number of time points.

    ags = zeros(1,n);
    % [] Pre-allocate acceleration magnitude in g's.

    for k = 1:n
        %— Earth‐fixed position
        Rcge = C.Rgse + Rcggs(:,k);

        %— gravity vector in ENZ
        g_vec = -C.Gm * Rcge / norm(Rcge)^3;

        %— inertial velocity in ENZ
        Vcge = C.Vgse + cross(C.We, Rcggs(:,k)) + Vcggs(:,k);

        %— drag force in ENZ
        Vatm = cross(C.We, Rcge);
        Vinf = Vcge - Vatm;
        vinf = norm(Vinf);
        [~,~,rho] = StandardAtmosphere(norm(Rcge)-C.Re);
        Fd = -0.5 * C.Cd * rho * C.acg * vinf * Vinf;

        %— net inertial acceleration (m/s^2)
        a_inert = Fd/C.mcg + g_vec;

        %— magnitude in g's
        ags(k) = norm(a_inert)/C.g;
    end
    % [] Loops over time, re-using exactly your EOM’s force & gravity code.

    Window = figure( ...
        'Color','w', ...
        'Name','Inertial Acceleration (Earth frame)', ...
        'NumberTitle','Off');
    % [] New white figure.

    Axes = axes( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'XLim',[0,70], ...
        'YLim',[0,20], ...
        'XTick',0:7:70, ...
        'YTick',0:2:20);
    % [] 12-pt bold Arial ticks every 7 s / 2 g

    plot(t, ags, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % [] Plot inertial accel vs. time.

    title(  'Inertial Acceleration', ...
            'FontName','Arial', ...
            'FontSize',20, ...
            'FontWeight','Bold');
    xlabel('Time (s)',     ...
           'FontName','Arial', ...
           'FontSize',16, ...
           'FontWeight','Bold');
    ylabel('Acceleration (g''s)', ...
           'FontName','Arial', ...
           'FontSize',16, ...
           'FontWeight','Bold');
end
