function PlotDynamicPressure(t, Rcggs, Vcggs, C)
% Plots Dynamic Pressure vs. Time
%
% Inputs:
%   t      – [1×n] time vector (s)
%   Rcggs  – [3×n] ENZ position w.r.t. GS (m)
%   Vcggs  – [3×n] ENZ velocity w.r.t. GS (m/s)
%   C      – constants struct

    n = numel(t);
    % [] Number of elements in the time vector.

    qkPa = zeros(1,n);
    % [] Pre‐allocate dynamic pressure in kPa.

    for k = 1:n
        % Earth‐fixed position
        Rcge = C.Rgse + Rcggs(:,k);
        h    = norm(Rcge) - C.Re;
        % get density at altitude
        [~,~,rho] = StandardAtmosphere(h);
        % inertial velocity
        Vcge = C.Vgse + cross(C.We, Rcggs(:,k)) + Vcggs(:,k);
        Vatm  = cross(C.We, Rcge);
        Vinf  = Vcge - Vatm;
        % dynamic pressure in Pa → kPa
        qkPa(k) = 0.5 * rho * norm(Vinf)^2 / 1e3;
    end
    % [] Loop re‐uses your EOM’s atmosphere & velocity code.

    Window = figure( ...
        'Color','w', ...
        'Name','Dynamic Pressure', ...
        'NumberTitle','Off');
    % [] New white figure.

    Axes = axes( ...
        'FontName','Arial', ...
        'FontSize',12, ...
        'FontWeight','Bold', ...
        'NextPlot','Add', ...
        'Parent',Window, ...
        'XGrid','On', ...
        'YGrid','On', ...
        'XLim',[0,70], ...
        'YLim',[0,500], ...
        'XTick',0:7:70, ...
        'YTick',0:50:500);
    % [] 12-pt bold Arial ticks every 7 s / 50 kPa

    plot(t, qkPa, ...
        'Color','k', ...
        'LineStyle','None', ...
        'Marker','.', ...
        'Parent',Axes);
    % [] Plot dynamic pressure vs. time.

    title(  'Dynamic Pressure', ...
            'FontName','Arial', ...
            'FontSize',20, ...
            'FontWeight','Bold');
    xlabel('Time (s)',      ...
           'FontName','Arial', ...
           'FontSize',16, ...
           'FontWeight','Bold');
    ylabel('Pressure (kPa)', ...
           'FontName','Arial', ...
           'FontSize',16, ...
           'FontWeight','Bold');
end
